[package]
authors = ['MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen <luke@mxc.org>']
build = 'build.rs'
edition = '2018'
name = 'datahighway'
version = '0.1.0'

[profile.release]
panic = "unwind"

[[bin]]
name = 'datahighway'
path = 'src/main.rs'

[dependencies]
futures = '0.3.1'
log = '0.4.8'
structopt = '0.3.8'
hex-literal = "0.2.1"
serde_json = "1.0.41"
codec = { package = "parity-scale-codec", version = "1.0.0" }
jsonrpc-core = "14.0.3"
serde = { version = "1.0.102", features = ["derive"] }

sc-basic-authorship = { version = '0.8.0-alpha.3' }
sc-cli = { version = '0.8.0-alpha.3' }
sc-client = { version = '0.8.0-alpha.3' }
sc-chain-spec = { version = '2.0.0-alpha.3' }
sc-client-api = { version = '2.0.0-alpha.3' }
sc-authority-discovery = { version = '0.8.0-alpha.3' }
sc-consensus-epochs = { version = '0.8.0-alpha.3' }
sc-consensus-babe = { version = '0.8.0-alpha.3' }
sc-consensus-babe-rpc = { version = '0.8.0-alpha.3' }
sc-executor = { version = '0.8.0-alpha.3' }
sc-finality-grandpa = { version = '0.8.0-alpha.3' }
sc-keystore = { version = '2.0.0-alpha.3' }
sc-network = { version = '0.8.0-alpha.3' }
sc-offchain = { version = '2.0.0-alpha.3' }
sc-rpc = { version = '2.0.0-alpha.3' }
sc-service = { version = '0.8.0-alpha.3' }
sc-telemetry = { version = '2.0.0-alpha.3' }
sc-transaction-pool = { version = '2.0.0-alpha.3' }
sp-api = { version = '2.0.0-alpha.3' }
sp-consensus-babe = { version = '0.8.0-alpha.3' }
sp-consensus = { version = '0.8.0-alpha.3' }
sp-core = { version = '2.0.0-alpha.3' }
sp-finality-grandpa = { version = '2.0.0-alpha.3' }
sp-inherents = { version = '2.0.0-alpha.3' }
sp-io = { version = '2.0.0-alpha.3' }
sp-runtime = { version = '2.0.0-alpha.3' }
sp-transaction-pool = { version = '2.0.0-alpha.3' }
substrate-frame-rpc-system = { version = '2.0.0-alpha.3' }
pallet-transaction-payment-rpc = { version = '2.0.0-alpha.3' }

datahighway-runtime = { version = '0.1.0', path = 'runtime' }

[build-dependencies]
vergen = '3.0.4'
build-script-utils = { version = '2.0.0-alpha.3', package = 'substrate-build-script-utils' }

[workspace]
members = [
    'runtime',
    'pallets/roaming/roaming-operators',
    'pallets/roaming/roaming-networks',
    'pallets/roaming/roaming-organizations',
    'pallets/roaming/roaming-network-servers',
    'pallets/roaming/roaming-devices',
    'pallets/roaming/roaming-routing-profiles',
    'pallets/roaming/roaming-service-profiles',
    'pallets/roaming/roaming-accounting-policies',
    'pallets/roaming/roaming-agreement-policies',
    'pallets/roaming/roaming-network-profiles',
    'pallets/roaming/roaming-device-profiles',
    'pallets/roaming/roaming-sessions',
    'pallets/roaming/roaming-billing-policies',
    'pallets/roaming/roaming-charging-policies',
    'pallets/roaming/roaming-packet-bundles',
    'pallets/mining/mining-speed-boosts/configuration/token-mining',
    'pallets/mining/mining-speed-boosts/configuration/hardware-mining',
    'pallets/mining/mining-speed-boosts/rates/token-mining',
    'pallets/mining/mining-speed-boosts/rates/hardware-mining',
    'pallets/mining/mining-speed-boosts/sampling/token-mining',
    'pallets/mining/mining-speed-boosts/sampling/hardware-mining',
    'pallets/mining/mining-speed-boosts/eligibility/token-mining',
    'pallets/mining/mining-speed-boosts/eligibility/hardware-mining',
    'pallets/mining/mining-speed-boosts/lodgements/token-mining',
    'pallets/mining/mining-speed-boosts/lodgements/hardware-mining',
]
exclude = [ "runtime/wasm" ]
