[package]
name = "lockdrop"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
sp-std = { version = '4.0.0-dev', default-features = false }

[features]
default = ['std']
std = [
    'sp-std/std',
]
