[package]
name = "lockdrop-runtime-api"
version = "0.1.0"
authors = ['Ilya Beregovskiy']
edition = "2021"

[dependencies]
sp-api = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.17', default-features = false}

[features]
default = ["std"]
std = [
	"sp-api/std",
]
