[package]
name = "lockdrop-rpc"
version = "0.1.0"
authors = ["Ilya Beregovskiy"]
edition = "2018"

[dependencies]
web3 = "0.13.0"
codec = { package = 'parity-scale-codec', version = '2.0.0', default-features = false, features = ['derive'] }
safe-mix = { version = '1.0.0', default-features = false }
frame-support = { version = '3.0.0', default-features = false }
frame-system = { version = '3.0.0', default-features = false }
pallet-balances = { version = '3.0.0', default-features = false }
pallet-randomness-collective-flip = { version = '3.0.0', default-features = false }
pallet-transaction-payment = { version = '3.0.0', default-features = false }
sp-core = { version = '3.0.0', default-features = false }
sp-io = { version = '3.0.0', default-features = false }
sp-runtime = { version = '3.0.0', default-features = false }
sp-std = { version = '3.0.0', default-features = false }

log = { version = '0.4.8' }
serde = { version = '1.0.101', optional = true, features = ['derive'] }

[dev-dependencies]
