[package]
name = 'module-primitives'
version = '3.0.5'
authors = ['Laminar Developers <hello@laminar.one>', 'MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen']
edition = '2018'

[dependencies]
serde = { version = '1.0.126', optional = true, features = ['derive'] }
codec = { version = '2.2.0', package = 'parity-scale-codec', default-features = false, features = ['derive', 'max-encoded-len'] }
sp-core = { git = 'https://github.com/paritytech/substrate', rev = '1d5abf01abafdb6c15bcd0172f5de09fd87c5fbf', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', rev = '1d5abf01abafdb6c15bcd0172f5de09fd87c5fbf', default-features = false }
bitmask = { version = '0.5.0', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', rev = '1d5abf01abafdb6c15bcd0172f5de09fd87c5fbf', default-features = false }

[features]
default = ['std']
std = [
    'bitmask/std',
    'codec/std',
    'serde',
    'sp-core/std',
    'sp-runtime/std',
    'sp-std/std',
]
