[package]
name = 'module-primitives'
version = '3.0.0'
authors = ['Laminar Developers <hello@laminar.one>', 'MXC Foundation GmbH <https://t.me/mxcfoundation>', 'Luke Schoen']
edition = '2018'

[dependencies]
serde = { version = '1.0.101', optional = true, features = ['derive'] }
codec = { version = '2.0.0', package = 'parity-scale-codec', default-features = false, features = ['derive'] }
bitmask = { version = '0.5.0', default-features = false }

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.9.12"

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.9.12"

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.9.12"

[features]
default = ['std']
std = [
    'bitmask/std',
    'codec/std',
    'serde',
    'sp-core/std',
    'sp-runtime/std',
    'sp-std/std',
]
